version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore TeamA/TeamA.csproj
  build:
    commands:
    - echo Build started on `date`
    - dotnet publish -c release -o ./build_output TeamA/TeamA.csproj
artifacts:
  files:
    - TeamA/build_output/**/*